server:
  port: 8081

spring:
  application:
    name: configdemo

  profiles:
    active: prod

  config:
    import: configserver:http://localhost:8082

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,health,info

build:
  id: 1000
  name: default
  type: default config type
  version: 1.0.0.1
